Верстка 2-х страниц в html
htmlacademy-htmlcss/521207-sedona-32 pull request #1
Opened 2021-09-28 12:29 UTC by ilyakeps

2021-09-29 07:08 UTC, lawejr requested changes

2021-09-29 07:08 UTC, lawejr commented on index.html
> +                    <input type="text" name="email">
На лекции в аналогичной ситуации вам рассказывали, что хорошо бы сделать скрытый `<label>`, чтобы было понятно для чего этот инпут. А так же добавить атрибут `placeholder`, чтобы подсказать пользователю в каком формате ожидается ввод значения.

2021-09-29 07:08 UTC, lawejr commented on index.html
> +                    <input type="text" name="email">
Кстати, у атрибута `type` есть значение `email`. Можно использовать его. Он разрешит браузеру автоматически предлагать варианты сохранённых адресов электронной почты, а на мобильных устройствах  покажет более подходящую клавиатуру для ввода email.

2021-09-29 07:08 UTC, lawejr commented on index.html
> +            <ul class="nav-image-center">
Здесь ситуация, аналогичная той, которую я описывал в шапке.
Так же не забудь поправить отступы.

2021-09-29 07:08 UTC, lawejr commented on index.html
> +                    <h2>+7 (812) 812-12-12
Номер телефона должен быть ссылкой, чтобы на него можно было кликнуть и позвонить. Посмотри, как это сделано на лекции.

2021-09-29 07:08 UTC, lawejr commented on index.html
> +                <pre>.html
Здесь будет просто картинка. Можно было бы сделать и текстом, но тогда бы ради одного слова пришлось подключать целый шрифт, что не совсем рационально.

2021-09-30 12:13 UTC, ilyakeps commented
отредактировал первую и вторую страницу

2021-10-01 07:42 UTC, lawejr requested changes

2021-10-01 07:42 UTC, lawejr commented on hotels.html
> +<header class="main-text">
Для этого хедера неплохо было бы создать общую секция с фильтрами поиска, т.к. у них по макету одинаковый фон

2021-10-01 07:42 UTC, lawejr commented on hotels.html
> +      <a href="index.html">Главная</a>
На макете нет такого текста. На этом месте иконка домика. Хорошо, что ты написал текст, но его нужно сделать скрытым.

2021-10-01 07:42 UTC, lawejr commented on hotels.html
> +            <input type="checkbox" name="bus" checked>
Это не ошибка, но "bus" переводится как "автобус". Для бассейна можно написать имя "pool", например. 
Транскрипции русских слов в именах классов/id/значениях атрибутов использовать нельзя по критериям.

2021-10-01 07:42 UTC, lawejr commented on hotels.html
> +            <input type="checkbox" name="parcing" checked>
Опечатка: "parcing". Должно быть "parking". 
Если не идеальное знание английского, рекомендуется пользоваться переводчиком и списком часто используемых слов, который давали на лекции https://github.com/yoksel/common-words.

2021-10-01 07:42 UTC, lawejr commented on hotels.html
> +            <input type="radio" name="type" value="appartaments">
apartment

2021-10-01 07:42 UTC, lawejr commented on hotels.html
> +      </button>
Перенос закрывающий тегов в такой ситуации не нужен. Подробно приводил примеры в комментариях к главной странице. Пройдись по всем файлам и проверь на предмет таких ошибок.

2021-10-01 07:42 UTC, lawejr commented on hotels.html
> +        <input type="text" name="price-text" id="field-price-text"> руб
Если `<input>` обёрнут в `<label>`, то указывать ему id для связи не нужно. id нужно указывать если тэги находятся отдельно друг от друга.

2021-10-01 07:42 UTC, lawejr commented on hotels.html
> +    <button type="button" class="button">
Для кнопки сброса формы есть специальный тип `type="reset"`. В таких ситуациях лучше использовать его.

2021-10-01 07:42 UTC, lawejr commented on hotels.html
> +      </section>
Нужно сделать в этой форме кнопку для отправки, как вам показывали на лекции. Чтобы форму можно было отправить без JS. Т.к. на макете кнопка не показана, её нужно сделать скрытой.

2021-10-01 07:42 UTC, lawejr commented on hotels.html
> +      <span class="visually-hidden">
Что-то не так с отступами в этом блоке

2021-10-01 07:42 UTC, lawejr commented on hotels.html
> +        Кнопка сортировки
Хорошо, что ты прописал ссылкам скрытые тексты, но лучше их сделать более понятными, например: "Показать карточки", "Показать подробно", "Показать списком". Иначе ссылкам с тремя одинаковыми текстами непонятно, куда они ведут и чем отличаются.

2021-10-01 07:42 UTC, lawejr commented on hotels.html
> +    <img src="" alt="картинка отеля" class="hotels-image">
Фото и названия отеля должны быть кликабельными ссылками, это можно увидеть в стайлгайде на макете https://www.figma.com/file/XTA1QAD4FQmJCRtbNbGbPb/HTML-1-Седона-32?node-id=476%3A200

2021-10-01 07:42 UTC, lawejr commented on hotels.html
> +  <div class="hotels1">
Этот блок с отелями очень похож на список. Например, "Список результатов поиска". Поэтому предлагаю сделать его через ul > li, а не просто `<div>`, который не несёт никакой смысловой нагрузки.

2021-10-01 07:42 UTC, lawejr commented on hotels.html
> +    <form class="hotels-form" action="https://echo.htmlacademy.ru/" method="post">
Форма была бы здесь уместна, если нужно отправлять на сервер какие-то значения. Но у тебя же в ней нет никаких полей ввода. Поэтому можно сделать это простой ссылкой, аналогично ссылке "Подробнее".

2021-10-01 07:42 UTC, lawejr commented on hotels.html
> +  </div>
Не вижу в разметке этих карточек блока с рейтингом, который по макету расположен в правой части. Есть проблемы с их разметкой?

2021-10-01 07:42 UTC, lawejr commented on hotels.html
> +          Предыдущяя страница
Не вижу в макете такой кнопки

2021-10-01 07:42 UTC, lawejr commented on hotels.html
> +  </div>
Пропущен блок со ссылкой "Загрузить ещё", который идёт после списка отелей.

2021-10-01 07:42 UTC, lawejr commented on hotels.html
> +    <button class="pages-button" type="button" name="download" class="bigtext">загрузить еще</button>
Эта кнопка должна быть выше по макету и сделана через тэг `<a>`

2021-10-01 07:42 UTC, lawejr commented on hotels.html
> +    <button class="pages-button" type="button" name="download" class="bigtext">загрузить еще</button>
Внутрь тэгов `<ul>` и `<ol>` можно вкладывать только `<li>` и никакие другие тэги

2021-10-01 07:42 UTC, lawejr commented on hotels.html
> +    <ul class="subscription-list">
Почему здесь использован список? Вроде нет никаких повторяющихся по смыслу элементов.

2021-10-01 07:42 UTC, lawejr commented on hotels.html
> +          <button type="button" name="button" id="email-button" class="bigtext">подписаться</button>
У кнопок которые отправляют форму должно быть другое значение `type`. См. комментарии на главной странице.

2021-10-01 07:42 UTC, lawejr commented on hotels.html
> +          <button type="button" name="button" id="email-button" class="bigtext">подписаться</button>
Для чего здесь прописан атрибут `id`?

2021-10-01 07:42 UTC, lawejr commented on hotels.html
> +<footer>
Футер на главной странице сделан с более качественно. Используй его на всех страницах, после того, как поправишь, оставленные там, замечания. 
Разметка и названия классов общих элементов, таких как `<header>`/`<footer>` должна быть аналогичной с минимальными расхождениями, чтобы можно было их стилизовать с помощью одинаковых классов и не дублировать css.

2021-10-04 14:29 UTC, ilyakeps commented
Переделал обе страницы, теперь смотрятся более качественно, вроде все должно быть так как в замечаниях.

2021-10-05 06:05 UTC, lawejr requested changes

2021-10-05 06:05 UTC, lawejr commented on hotels.html
> +      <button class="loading-button" type="button">Загрузить еще</button>
Атрибут `title` у кнопки нужен, только когда у неё нет `href`, чтобы подсказать пользователю, почему так происходит. Если `href` есть, то `title` избыточен.

2021-10-05 06:05 UTC, lawejr commented on hotels.html
> +              <input type="checkbox" name="pool" checked>Бассейн</label>
Снова форматирование поехало :(
Закрывающий тэг </label> должен быть на отдельной строке.

2021-10-05 06:05 UTC, lawejr commented on index.html
> +        <p class="causes-two-list-item-one">
Если в тэг `p` не вложено никакого текста, то нет смысла оборачивать в него картинку. Всё-таки `<p>` - это текстовый тэг и он должен содержать в себе какой-то текст.

2021-10-05 06:05 UTC, lawejr commented on index.html
> +          <img src="" alt="картинка еды">
Эти картинки являются декоративными и правильней сделать их через css с помощью фона позже, чтобы не выделять под них отдельный тэг.

2021-10-05 07:14 UTC, merged